# Generated by Django 4.2.25 on 2025-10-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sales_priority',
            field=models.IntegerField(default=0, help_text='Higher number means higher priority on homepage'),
        ),
    ]
