# Generated by Django 4.2.25 on 2025-10-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_sales_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Available quantity'),
        ),
    ]
