# Generated by Django 4.2.25 on 2025-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The personal email address (e.g., Gmail) of the staff member to grant dashboard access.', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional: Name of the staff member for reference.', max_length=100, null=True)),
                ('role', models.CharField(blank=True, help_text="Optional: Role like 'Store Manager', 'Incharge' etc.", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Authorized Staff Email',
                'verbose_name_plural': 'Authorized Staff Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
