# Generated by Django 4.2.25 on 2025-10-24 19:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Account',
                'verbose_name_plural': 'Staff Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
