# Generated by Django 4.2.25 on 2025-10-30 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(blank=True, help_text='e.g., TS01AB1234', max_length=50, null=True)),
                ('current_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery')], default='OFFLINE', max_length=20)),
                ('last_known_latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('last_known_longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riderprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rider Profiles',
            },
        ),
    ]
